version: '3'  # version of compose format 

services:
  laptop-service:
    build: ./laptop  
    volumes:
      - ./laptop:/usr/src/app 
    ports:
      - "5002:80"  # host:container
  db:
    image: mongo:latest
    ports:
      - "5003:27017"

  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - "5001:80"  # host:container
    depends_on:
      - laptop-service  # website is not going to work unless laptop-service is running

  brevet:
    build: ./brevet_calculator
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/brevet
    links:
      - db
