version: '3'  # version of compose format 

services:
  api-service:
    build: ./api
    volumes:
      - .:/workspace:cached
    environment:
      - PYTHONUNBUFFERED=1
#    ports:
#      - "5002:80"  # host:container
  db:
    image: mongo:latest
    ports:
      - "5003:27017"  # for MongoDB compass

  brevet:
    build: ./brevet_calculator
    command: python -u app.py
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/workspace:cached
    links:
      - db
    environment:
      - PYTHONUNBUFFERED=1
